-- Admin access schema for Supabase (matches existing table shape)
-- Run this in Supabase SQL editor.

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Keep migration re-runnable for existing deployments.
alter table public.admin_users
  add column if not exists id bigint generated by default as identity,
  add column if not exists user_id uuid,
  add column if not exists created_at timestamptz not null default now();

alter table public.admin_users
  alter column user_id set not null;

-- One admin row per auth user.
create unique index if not exists admin_users_user_id_uidx on public.admin_users (user_id);

alter table public.admin_users enable row level security;

-- Admin users can read their own row.
drop policy if exists "admin_users_select_own" on public.admin_users;
create policy "admin_users_select_own"
  on public.admin_users
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Only service role should insert/update/delete admin rows from secure backend tooling.
drop policy if exists "admin_users_no_client_write" on public.admin_users;
create policy "admin_users_no_client_write"
  on public.admin_users
  for all
  to authenticated
  using (false)
  with check (false);

create or replace function public.is_admin(p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.user_id = p_user_id
  );
$$;

revoke all on function public.is_admin(uuid) from public;
grant execute on function public.is_admin(uuid) to authenticated;

comment on function public.is_admin(uuid)
  is 'Checks whether the provided auth user has an admin_users row.';
